### ISSUE TITLE
From user testing: [Beneficiari] error at adding a beneficiary in db

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#100]
**Describe the bug**
5 out of 12 users reported that when they added the beneficiary in db they got the error that the CNP already exists in db even though the CNP was the beneficiary's real data and it has never been added in db before. 
Please check why this may happen

**Comment by andreiio** [comment]
this means another beneficiary with the same CNP was introduced by a different user. this doens't sound like a bug, but rather an issue with the data they're trying to input.

**Comment by teodoranegru** [comment]
Can no longer reproduce the behavior
