### ISSUE TITLE
From user testing: [Acasă] ,,Programări'' stats card doesn't update

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#103]
**Describe the bug**
If the user adds a new appointment, the counter from the ,,Programări'' stats card doesn't update.

**To Reproduce**
1. Go to 'Acasă' section
2. Notice the number displayed in the 'Programări' stats card
3. Click on 'Adaugă programare'
4. Click on 'Creare' button
5. Go to 'Acasă' section from the top main navigation
6. Notice the number displayed in the 'Programări' stats card

**Expected behavior**
When an appointment is created in the db, it should be taken into account and displayed in the 'Programări' stats card from the 'Acasă' section

**Comment by andreiio** [comment]
This currently takes into account the actual appointment date, not date when the appointment was created. This can be easily changed, but I need confirmation this is actually desired.

**Comment by teodoranegru** [comment]
Take into account the actual appointment date. The issue is obsolete because the behavior is already implemented.
