### ISSUE TITLE
From user testing: [Beneficiari/Catagrafie] wrong values displayed for 'Medic de familie' field

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#108]
Describe the bug
Values displayed for 'Medic de familie' field at the moment are: _Neînscris la medic de familie; Coasigurat;_

Expected behavior
Replace the existing values with the ones from the [data dictionary](https://docs.google.com/spreadsheets/d/14C7lMpLjVdXnwh_0YUZiVzAd0KHDaktSvXaa1a5xIhk/edit#gid=558689725): _Neînscris la medic de familie; Înscris la medic de familie_

**Comment by andreiio** [comment]
Related to this issue, we also have duplicate vulnerability ids:


| Category                      | Vulnerabilities                                                                  |
| :---------------------------- | :------------------------------------------------------------------------------- |
| Asigurare socială de sănătate | Neasigurat (VSA_01)<br>Coasigurat (VSA_98)<br>**Asigurat (VSA_99)**                  |
| Medic de familie              | Neînscris la medic de familie (VSA_02)<br>**Înscris la medic de familie (**VSA_99**)** |

One of these two needs to be renamed to something different from `VSA_99`. Let's check if both categories should have the `VSA_` prefix.

**Comment by teodoranegru** [comment]
New prefix for Medic de familie category:
Neînscris la medic de familie (VFD_02); Înscris la medic de familie (VFD_99)

**Comment by teodoranegru** [comment]
Neînscris la medic de familie (VSA_02); Înscris la medic de familie (VSA_97)
