### ISSUE TITLE
Determine Coordonator judetean permissions 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#137]
To determine Coord jud permissions. Take in consideration that:
- CJ should be able to crud amc accounts
- CJ should be able to change password of an account
- CJ should be able to transfer beneficiaries from one account to another??

**Comment by andreiio** [comment]
CJ = admin with county restrictions

TODO: 
- [ ] add multi role support for user resource;
- [ ] add location columns to `CommunityActivity` model;


TBD:

1. coordonatorul poate fi alocat pe mai multe județe?

**Comment by teodoranegru** [comment]
TBD:
- Cine defineste aria de acoperire a asistentului?
- UN AMC POATE SA ISI DESFASOARE ACTIVITATE IN LOCALITATI DIN JUDETE DIFERITE?

**Comment by teodoranegru** [comment]
This issue is obsolete. The role has been defined. For other enhancements regarding the _Coordonator_ user type we will open new issues. @andreiio please close the issue if you are done with it.
