### ISSUE TITLE
[AMC/Beneficiar/Arhivă documente] error at saving uploaded file

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#160]
When you try to save the uploaded file (pdf, 185 KB), it displays this error:

![image](https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/81ffbe9a-52a1-448e-bb96-add5b9007750)

After you close the error, it displays the created items in the table

![image](https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/569cb9a5-dc21-48d5-a5f5-c170364d5a59)

When you try to open one of the documents from the table, it displays this error:

![image](https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/57c3b12b-c45b-47b2-aef9-65a0ec733ca7)

**Comment by teodoranegru** [comment]
Issue is still valid

**Comment by teodoranegru** [comment]
I still can't view the document after adding it 
![image](https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/322fd72c-a53a-4187-8cdb-8940fa4d4090)

**Comment by andreiio** [comment]
It wasn't deployed yet
