### ISSUE TITLE
[AMC/ Catagrafie] values from the form not displayed in view mode

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#177]
The values configured in Catagrafie/Dizabilități - detalii and Catagrafie/Stare de sănătate - detalii sections are not displayed in view mode, neither in Formular catagrafie (view mode) nor in Sumar vulnerabilități section. 

The values should be displayed as depicted below:
 
![image](https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/d6b0304c-db2a-4e8f-a010-a84ed64f2c29)
![image](https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/158ff46a-72a6-444e-ad5e-01d8cfc96060)

**Comment by andreiio** [comment]
Related to #109 and #110
