### ISSUE TITLE
[AMC/Beneficiari/Interventii] the value in the Vulnerabilitate adresată field disappears in edit mode

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#236]
When you edit an existing service/management de caz and enter edit mode, the value from Vulnerabilitate adresată field disappears.

https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/73e144b4-27b1-4b2f-9e79-e06d60fb4fa5

**Comment by andreiio** [comment]
This is related to #176. Both require reworking the way we build the vulnerabilities list.
