### ISSUE TITLE
Boală rară: [AMC/Beneficiari/Catagrafie] implement "Suspiciuni (opțional)" sub-section

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#249]
Implement a new sub-section that behaves as a repeater in the Catagrafie form, named "Suspiciuni (opțional)". 
The sub-section will contain the following fields:
1. "Suspiciune de" - input field
2. "Categorie suspiciune" - single select; field values: Boală rară; Altă categorie;
2.2 **IF Boală rară selected, display the following field:** 
"Elemente de suspiciune" - multiple select; (see values in the data dictionary)
3. "Alte elemente de suspiciune" - input field;

See more details in data dictionary

(https://docs.google.com/spreadsheets/d/14C7lMpLjVdXnwh_0YUZiVzAd0KHDaktSvXaa1a5xIhk/edit#gid=558689725)
See design [here ](https://www.figma.com/file/XRFocirDCObY8DimA0wGBr/Asistent-Medical-Comunitar?type=design&node-id=5593-33508&mode=design&t=5S36P0YkiJihsoiT-4)

**Comment by andreiio** [comment]
1. Do we expect să extindem opțiunile pentru `Categorie suspiciune`? Dacă da, trebuie codificate valorile la fel ca la vulnerabilități.
2. Valorile pentru `Elemente de suspiciune` trebuie și ele codificate.
3. Sunt suspiciuni de boli rare sau boli cronice? Aici folosești boală cronică, în figma boală rară, și în data dictionary both.

**Comment by teodoranegru** [comment]
> 1. Do we expect să extindem opțiunile pentru `Categorie suspiciune`? Dacă da, trebuie codificate valorile la fel ca la vulnerabilități. - Done
> 2. Valorile pentru `Elemente de suspiciune` trebuie și ele codificate. - Done 
> 3. Sunt suspiciuni de boli rare sau boli cronice? Aici folosești boală cronică, în figma boală rară, și în data dictionary both. - Done
> 4. Cum afișăm suspiciunile în view mode? - Discussed
