### ISSUE TITLE
[AMC/Beneficiari/Catagrafie] wrong hour displayed in Sumar vulnerabilități section

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#272]
At the end of  Sumar vulnerabilități section in the Catagrafie page, the date and hour when the Catagrafie was created and when it was latest edited is displayed. 

The hours displayed do not match the user's time zone. It is 3 hours earlier. 
![image](https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/952a65be-3d5b-4116-ae60-8146c6a2e622)

**Comment by andreiio** [comment]
This was a problem on the staging server only. The production server had the timezone properly set to `Europe/Bucharest`.
