### ISSUE TITLE
[AMC/Beneficiari ocazionali] error at accesing Date personale 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#291]
If you modify beneficiary type from Ocazional to Propriu and the beneficiary has no data (Identitate necunoscută beneficiar checked), when you try to access Date personale section of that beneficiary it displays the error below: 
![image](https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/1127676e-1749-46b7-a863-f96d2655d194)

**Comment by andreiio** [comment]
Fixed in #293
