### ISSUE TITLE
[AMC/Beneficiari/Intervenții] eliminate values from the list of services

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#292]
Eliminate the following values from the list of services (it is also marked with red in the data dictionary/Interventii (Servicii) sheet, at the end):
SNA_01
SNA_02
SNA_03
SNA_04
SNA_05
SAA_01
SAA_02
SAA_03
SAA_04
SAA_05
SAA_06
SAN_01
SAN_02
SAN_03

**Comment by andreiio** [comment]
Not removing, just disabling
