### ISSUE TITLE
[AMC/Beneficiar/Inteventii] Abordare integrata=YES from a service within a MDC is saved with the value NO

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#302]
**Describe the bug**
When the user creates a service within a Management de caz and ticks Abordare integrata=YES, when the user saves the service, the Abordare integrata field is saved with the value NO.

**Comment by andreiio** [comment]
is this still happening? can't reproduce locally

**Comment by teodoranegru** [comment]
> is this still happening? can't reproduce locally

Can't reproduce it either. I will close the ticket
