### ISSUE TITLE
[AMC/Beneficiar/Intervenții/Management de caz] the data entered in 'Descriere/Observații' field from a service within an MDC intervention is not saving

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#304]
**Describe the bug**
When the user adds a service in a case management intervention, they add data in the "Detalii/Observatii" field, but that data does not save. 

[err service .webm](https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/0a06a47e-377b-42d6-af12-e11c2ad34094)

**Comment by andreiio** [comment]
Can't seem to reproduce it anymore. Will keep monitoring

**Comment by teodoranegru** [comment]
> Can't seem to reproduce it anymore. Will keep monitoring

Still not working for me
