### ISSUE TITLE
[Beneficiar - Overview] wrong information displayed in ''Intervenții active'' section

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#52]
**Describe the issue:**
When you access a beneficiary's profile, in the _Overview_ page, there is the ''Intervenții active'' section/table. We can notice that in the table there are displayed multiple interventions from other beneficiaries, right from the beginning, when the beneficiary don' even has any interventions created. This is very confusing for the end users because it mixes the information about beneficiaries. 

**To Reproduce
Steps to reproduce the behavior:**
1. Go to _Listă beneficiari_ page
2. Access any permanent beneficiary's profile
3. Notice the ''Intervenții active'' section and the data displayed in it

![image](https://github.com/code4romania/asistent-medical-comunitar/assets/102228836/edd5fba5-b406-4b9f-bf83-0a5f2c8d5ad0)

**Expected behavior:**
Active interventions table should contain a table component that will display data about all the active interventions ADDED TO THAT BENEFICIARY (Case managements with STATUS= Open & Individual services with STATUS = Planificat).

**Comment by andreiio** [comment]
`Intervenții active` queries for the wrong beneficiary

**Comment by andreiio** [comment]
`Intervenții active` should only show:

- Servicii planificate
- Management de caz deschis
