### ISSUE TITLE
[Intervenții] wrong status for interventions TYPE = Intervenție beneficiar ocazional

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#55]
**Describe the bug**
All interventions TYPE = Intervenție beneficiar ocazional have STATUS = Deschis. All interventions of this type must have STATUS = Închis, because the user can't edit it anymore.  The wrong status may affect other sections that query active interventions. 

**To Reproduce**
1. Go to _Listă beneficiari_ section
2. Click on an occasional beneficiary that has at least one intervention added
3. Click on ''Modifică tipul beneficiarului'' button
4. Click on ''Modifică'' button
5. Go to _Intervenții_ section
6. Expand table
7. Notice that all intervention TYPE =  Intervenție beneficiar ocazional have STATUS = Deschis

**Expected behavior*˙*
All interventions TYPE =  Intervenție beneficiar ocazional  must have STATUS = Închis.

**Comment by andreiio** [comment]
This fix only applies to future beneficiary conversion
