### ISSUE TITLE
[Profilul meu] no confirmation message when deleting an employer

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#60]
**Describe the bug**
When you delete an employer from _Profilul meu/Angajatori_ section there is no confirmation message displayed, it deletes the entity instantly and there is no undo. 

**To Reproduce**
1. Go to _Profilul meu_
2. Go to _Angajatori_ section
3. Click on ''Editează'' button
4. Click on the delete icon/button
5. Notice the absence of the confirmation message

**Expected behavior**
When you click on the delete button it should be displayed a confirmation message consistent with the ones used across the platform.

**Comment by andreiio** [comment]
This is not currently supported by the repeater component we're using for this section.

Same as #59
