### ISSUE TITLE
[Profilul meu] no confirmation message when deleting an area

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/asistent-medical-comunitar#61]
**Describe the bug**
When you delete a study from _Profilul meu/Arie acoperită_ section there is no confirmation message displayed, it deletes the entity instantly and there is no undo. 

**To Reproduce**
1. Go to _Profilul meu_
2. Go to _Arie acoperită_ section
3. Click on ''Editează'' button
4. Click on the delete icon/button
5. Notice the absence of the confirmation message

**Expected behavior**
When you click on the delete button it should be displayed a confirmation message consistent with the ones used across the platform.

**Comment by andreiio** [comment]
This is not currently supported by the repeater component we're using for this section.

Same as #59
